### ISSUE TITLE
LS_COLORS broken

### ISSUE THREAD

**Issue by m-ou-se** [m-ou-se/config#10]
@de-vri-es: Looks like the 'real' `ls` doesn't understand your new LS_COLORS:

```
$ /bin/ls -l --color=always
/bin/ls: unparsable value for LS_COLORS environment variable
```

**Comment by m-ou-se** [comment]
Maybe it's also not a great idea to list all these files (`Makefile`, `Cargo.toml`, etc.) in our `shellrc`, as this list would have to be kept in sync with the list `exa` kees internally.

**Comment by m-ou-se** [comment]
Reverted 5ca2571 to fix this issue.

**Comment by de-vri-es** [comment]
Moved them to `EXA_COLORS` instead. It may not be nice to duplicate the the list, but the list in exa isn't complete anyway. And I think there is an important enough difference between build definition files and READMEs to show them differently.
