### ISSUE TITLE
LS_COLORS unparsable

### ISSUE THREAD

**Issue by kvdeurzen** [m-ou-se/config#11]
I get the following error when using any form related to `ls`:
ls: unparsable value for LS_COLORS environment variable

Commenting out the content of dircolors does not solve the problem. However commenting the following lines in shellrc does solve the issue after a relogin:
```
# if test_command dircolors; then
#     test -r "$config_dir/dircolors" && eval "$(dircolors -b "$config_dir/dircolors")" || eval "$(dircolors -b)"
# fi
```
 
Strangely enough the resulting LS_COLORS based on both changes seems exactly the same.

I've also observed that line 58 in shellrc introduces a unnecessary colon. Removing it however also doesn't solve the issue.

I'm using zsh by the way, however switching to bash gives the same error.

**Comment by m-ou-se** [comment]
Thanks for opening this issue!

I just ran into the exact same issue, and opened #10 for this. Closing this as a duplicate.
