### ISSUE TITLE
Title doesn't update when not changing directories

### ISSUE THREAD

**Issue by m-ou-se** [m-ou-se/config#6]
# Title is 'maurice@box: ~'
    $ ssh foobar
    # Title changes to 'maurice@foobar: ~'
    $ exit
    # Title is still 'maurice@foobar: ~' <- This is wrong.
    $ cd foo
    # Title changes to 'maurice@box: ~/foo'

**Comment by de-vri-es** [comment]
Should be fixed by #7 for zsh
